harmony_admin:
    # Models
    models:
        user:
            class: Symfony\Component\Security\Core\User\UserInterface
            label: 'users'
            list:
                fields:
                    - 'username'
                    - 'email'
                    - 'roles'
                    - 'isLocked'
            form:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: Symfony\Component\Form\Extension\Core\Type\TextType, type_options: { required: false } }
                    - { property: 'roles' }