harmony_admin:
    # Models
    models:
        user:
            translation_domain: 'UserBundle'
            class: Symfony\Component\Security\Core\User\UserInterface
            label: 'admin.users'
            list:
                fields:
                    - { property: 'username', label: 'admin.username' }
                    - { property: 'email', label: 'admin.email' }
                    - { property: 'groups', type: 'array', label: 'admin.groups' }
                    - { property: 'getUserRoles', type: 'array', label: 'admin.roles' }
                    - { property: 'isLocked', label: 'admin.is_locked' }
            form:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: Symfony\Component\Form\Extension\Core\Type\TextType, type_options: { required: false } }
                    - 'groups'
                    - { property: 'getUserRoles', type: Harmony\Bundle\UserBundle\Form\Type\UserRoleType }

        group:
            translation_domain: 'UserBundle'
            class: Harmony\Bundle\UserBundle\Group\GroupInterface
            label: 'admin.groups'
            list:
                fields:
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'roles', type: 'array', label: 'admin.roles' }
            form:
                fields:
                    - 'name'
                    - { property: 'roles', type: Harmony\Bundle\UserBundle\Form\Type\UserRoleType }