harmony_admin:
    # Models
    models:
        user:
            class: Symfony\Component\Security\Core\User\UserInterface
            label: 'users'
            list:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'roles', type: 'array' }
                    - 'isLocked'
            form:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: Symfony\Component\Form\Extension\Core\Type\TextType, type_options: { required: false } }
                    - { property: 'roles', type: Harmony\Bundle\UserBundle\Form\Type\UserRoleType }

        group:
            class: Harmony\Bundle\UserBundle\Group\GroupInterface
            label: 'groups'
            list:
                fields:
                    - 'name'
                    - { property: 'roles', type: 'array' }
            form:
                fields:
                    - 'name'
                    - { property: 'roles', type: Harmony\Bundle\UserBundle\Form\Type\UserRoleType }