services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $userClass: '%harmony_user.user_class%'

    Harmony\UserBundle\Security\UserProvider:
        public: false

    Harmony\UserBundle\Form\Type\RegistrationFormType: ~

    Harmony\UserBundle\Model\UserManager: ~

    Harmony\UserBundle\Controller\RegistrationController: ~

    Harmony\UserBundle\Controller\SecurityController: ~

    Harmony\UserBundle\Controller\PasswordController:
        arguments:
            $resetTokenTtl: '%harmony_user.password_reset.token_ttl%'

    Harmony\UserBundle\Event\UserEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Harmony\UserBundle\Security\UserChecker: ~

    Harmony\UserBundle\Mailer\TwigSwiftMailer:
        arguments:
            $mailer: '@mailer'
            $parameters: { email_from: '%harmony_user.password_reset.email_from%' }
