services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $userClass: '%harmony_user.user_class%'

    Harmony\Bundle\UserBundle\Security\UserProvider:
        public: false

    Harmony\Bundle\UserBundle\Form\Type\RegistrationFormType: ~

    Harmony\Bundle\UserBundle\Manager\UserManager: ~
    Harmony\Bundle\UserBundle\Manager\UserManagerInterface: '@Harmony\Bundle\UserBundle\Manager\UserManager'

    Harmony\Bundle\UserBundle\Controller\RegistrationController: ~

    Harmony\Bundle\UserBundle\Controller\SecurityController: ~

    Harmony\Bundle\UserBundle\Controller\PasswordController:
        arguments:
            $resetTokenTtl: '%harmony_user.password_reset.token_ttl%'

    Harmony\Bundle\UserBundle\Event\UserEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Harmony\Bundle\UserBundle\Security\UserChecker: ~

    Harmony\Bundle\UserBundle\Mailer\TwigSwiftMailer:
        arguments:
            $mailer: '@mailer'
            $parameters: { email_from: '%harmony_user.password_reset.email_from%' }

    Harmony\Bundle\UserBundle\Command\CreateUserCommand: ~
    Harmony\Bundle\UserBundle\Command\PromoteUserCommand: ~

    Harmony\Bundle\UserBundle\Form\Type\UserRoleType:
        arguments:
            $roleHierarchy: '%security.role_hierarchy.roles%'